name: Execução automação de testes

on:
  workflow_dispatch:
    inputs:
      amb:
        description: 'Selecionar algum destes ambientes: dev / hml / prd'
        required: false
        default: 'hml'
      browser:
        description: 'Selecionar algum destes browsers: chrome / electron'
        required: false
        default: 'chrome'
      tag:
        description: 'Selecionar alguma tag, por exemplo: @regressivo / @smoke / @login'
        required: false
        default: '@regressivo'
  pull_request:
    branches: [ master, development ]
  schedule:
    - cron: "0 0 * * *"
    
env:
  DEFAULT_AMB: "hml"
  DEFAULT_BROWSER: "chrome"
  DEFAULT_TAG: "@regressivo"

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome90-ff88
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run: npm install
      - uses: actions/checkout@v2
      - name: Cypress run 
        uses: cypress-io/github-action@v2
        with:
          working-directory: nodejsmodel
          command: npx cypress run
          # --config-file config/${{github.event.inputs.amb || env.DEFAULT_AMB}}.json --browser ${{github.event.inputs.browser || env.DEFAULT_BROWSER}} --env grepTags=${{github.event.inputs.tag || env.DEFAULT_TAG}}
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history